### ISSUE TITLE
Mobiletoken fase 1: Bruk av mobiltoken i app

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/leveranser#1]
Mål: 
- Avvikle bruk av papir-QRkoder i appen
- Oppnå at de fleste billettkjøp skjer i innlogget tilstand. 

Hensikt:
- Risiko/mye støy i fht. forelenge med WTW.
- Inntektssikring for AtB.
- Øke kundetilfredshet ved å tilby flere billettprodukter i appen.  
- OOS-partnere har en forventning om at vi løser dette.

### Features:

**Fase 1:**
Introdusere mobile-token til en liten brukermasse, folk som vi har kontroll på. Introdusere beta-koder og ha dialog via Intercom. Ikke for folk flest (med t-kort eller e-post innlogging i nettbutikk).

#### MittAtB
- [x] https://github.com/AtB-AS/mittatb-app/issues/1087 @rosvik @hildeor @tormoseng 
- [x] https://github.com/AtB-AS/mittatb-app/pull/1589 @cbrevik 
- [x] Generere et mobile-token når brukeren logger inn (avhengig av SDK-integrasjon i appen)
- [x] Vise mobile-token QR-kode i billettdetaljer om brukeren har mobile-token på telefon, ellers default til papir QR-kode
- [x] Tilgjengeliggjøring av periodebilletter (avhengig av Entur produktregister, undersøke med Gunn om mer må gjøres i produksjon)
	- En og samme invitasjonskode skru på periodebilletter, samtidig som den skrur på mobile-token
	- Alle periodebilletter? Avsjekke med Gunn at alle er klar / funker
	- Kjøre noen tester 

#### SDK
- [x] https://github.com/AtB-AS/abt-swift-test/pull/50 @cbrevik (lande denne, blocker på JS SDK)
- [x] https://github.com/AtB-AS/abt-tokens/pull/11 (Lande denne). @havwig @gorandalum
- [x] https://github.com/AtB-AS/abt-swift-test/issues/2 (ferdigstille) @brorhb @gorandalum 
- [x] https://github.com/AtB-AS/abt-swift-test/issues/34 @cbrevik @gorandalum  
- [x] https://github.com/AtB-AS/abt-swift-test/issues/33 @brorhb  
- [x] https://github.com/AtB-AS/abt-swift-test/issues/29 (+ iOS) @monopoint 

### Avklaringer
- [x] Inntektssikring, dobbel innloggin. @cbrevik snakker med Jahn Erik
- [x] Sikre at abt-tokens kjører med rett versjon i staging @havwig @gorandalum 
- [x] Teste eksisterende demo-app for mobile-token SDK + inspektørapp @tormoseng 
- [x] Avsjekke hvordan mobile-token skal inspiseres på tog - MT for tog skal støtte QR-kode basert på mobile-token. Rullet ut på tog? - høre med Gunn og Trond
- [x] Testgruppa (pilotkunder) på fase 1
- [x] Teknisk utredning hvordan vi skal håndtere at folk mister aktive billetter ved innlogging @rosvik 
- [x] (Potensielt) Konsept folk mister aktive billetter i overgang fra anonymt til innlogget @hildeor 
- [x] Sette metadata i Intercom på hvem som har mobile-token
- [x] Sette metadata på token status
- [x] Sendt ut kommunikasjon om hvordan de laster ned appen fra TestFlight
- [x] Formell invitasjon til demo på fredag
- [x] ~Skru av QR-kodegenerering hvis du har mobile-token?~ Ikke viktig for fase 1 siden sikkerhetsnivå ikke blir påvirket av papir-QR-koder

**Comment by brorhb** [comment]
Har vi noen formening om tidsperioder på fase 1, 2 og 3? 😊

**Comment by cbrevik** [comment]
> Har vi noen formening om tidsperioder på fase 1, 2 og 3? 😊

Skal ha et møte om produktinitiativ denne uka hvor jeg håper vi lander på noen datoer. Men fase 2 innen utgangen av oktober er noe jeg håper på.
