### ISSUE TITLE
Synliggjøre flextilbud ved reisesøk, med info om hvordan man bestiller

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/leveranser#66]
### Mål

- snip

### Hensikt

- snip

### Første løsning som rulles ut i produksjon som gir en målbar endring/gevinst

- snip

### Features
- [ ] https://github.com/AtB-AS/mittatb-app/issues/1111

**Comment by jahnrohme** [comment]
https://github.com/AtB-AS/leveranser/issues/66
